spring:
  application:
    name: provide-service

dubbo:
  scan:
    base-packages: com.gu.provider
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://192.168.40.128:8848
server:
  port: 8083





